name: Build all gamaPhy keyboards

on:
  push:
    branches:
      - "actions"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install QMK
      run: python3 -m pip install qmk

    - name: Setup QMK
      run: yes | ./in_qmk qmk setup
    
    - name: Build keyboards
      run: ./in_qmk.sh qmk mass-compile -f keyboard_folder='gamaphy/*' -km via -j 0

    - run: cat qmk_firmware/.build/failed*

    - uses: marvinpinto/action-automatic-releases@latest
      if: always()
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Latest Firmware"
        files: |
          qmk_firmware/*.hex
          qmk_firmware/*.bin
          qmk_firmware/*.uf2
